# OSX and Windows work, just commented to save Travis resources
language: minimal
group: travis_latest
dist: xenial

git:
  depth: 3
  quiet: true

env: FC=gfortran

addons:
  apt:
    sources: ubuntu-toolchain-r-test
    packages:
    - gfortran-6
    - octave

matrix:
  include:
  - os: linux
    env: FC=gfortran-6
#  - os: osx
#    before_install:
#    - brew update > /dev/null
#    - brew install gcc > /dev/null
#  - os: windows
#    install:
#    - cd build
#    - cmake -G "MinGW Makefiles" -DCMAKE_SH="CMAKE_SH-NOTFOUND" ..
#    - cmake --build .

install:
- cmake -B build -S .
- cmake --build build -j

script:
- cd $TRAVIS_BUILD_DIR/build
- ctest --output-on-failure
